#pragma once
#ifndef __GAME_OBJECT_TYPE__
#define __GAME_OBJECT_TYPE__
enum class GameObjectType {
	NONE = -1,
	AGENT,
	PATH_NODE,
	SPACE_SHIP,
	OBSTACLE,
	SHIP,
	TARGET,
	PLAYER,
	PLANE,
	START_BUTTON,
	RESTART_BUTTON,
	BACK_BUTTON,
	NEXT_BUTTON,
	BACKGROUND,
	NUM_OF_TYPES,
	LEVEL_SELECT_BUTTON,
	CONTROLS_BUTTON,
	LEVEL_ONE_BUTTON,
	LEVEL_TWO_BUTTON,
	LEVEL_THREE_BUTTON
};
#endif /* defined (__GAME_OBJECT_TYPE__) */